### ISSUE TITLE
[ASK] Whatsapp Dekstop Feature

### ISSUE THREAD

**Issue by arifals27** [xanmoy/whatsapp-desktop-client#3]
Can I use voice calls or video calls like on WhatsApp desktop on Windows?

**Comment by xanmoy** [comment]
Currently, since my open-source WhatsApp Desktop is built on top of WhatsApp Web, it doesn't support voice or video calls. This is because WhatsApp officially does not provide audio or video calling features for WhatsApp Web. As a result, those features are not available in the desktop version either at this time.
